{% set name = "glow-md" %}
{% set version = "2.1.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/charmbracelet/glow/archive/v{{ version }}.tar.gz
  sha256: f13e1d6be1ab4baf725a7fedc4cd240fc7e5c7276af2d92f199e590e1ef33967

build:
  number: 0

requirements:
  build:
    - {{ compiler('go-nocgo') }}
    - go-licenses

test:
  commands:
    - glow --help

about:
  home: https://github.com/charmbracelet/{{ name }}
  license: MIT
  license_file:
    - LICENSE
    - license-files/
  summary: Render markdown on the CLI
  dev_url: https://github.com/charmbracelet/{{ name }}

extra:
  recipe-maintainers:
    - danielnachun
