schema_version: 1

context:
  version: "2.1.2"

package:
  name: glow-md
  version: ${{ version }}

source:
  url: https://github.com/charmbracelet/glow/archive/v${{ version }}.tar.gz
  sha256: 1b933139da1d08647bf5b3f112cab9548fdc2b40c056c7fa3d84d8706de5265a

build:
  number: 0
requirements:
  build:
    - ${{ compiler('go-nocgo') }}
    - go-licenses

tests:
  - script:
      - glow --help

about:
  license: MIT
  license_file:
    - LICENSE
    - license-files/
  summary: Render markdown on the CLI
  homepage: https://github.com/charmbracelet/glow
  repository: https://github.com/charmbracelet/glow

extra:
  recipe-maintainers:
    - danielnachun
